apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: phishing
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass123"
  MYSQL_DATABASE: "phishing_database"
  MYSQL_USER: "demo"
  MYSQL_PASSWORD: "demo"
  DB_HOST: "mysql-service"
  DB_USER: "demo"
  DB_PASSWORD: "demo"
  DB_NAME: "phishing_database"
